name: Push

on:
  push:
    tags-ignore:
      - '*'
  pull_request:

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run docker-build local action
        uses: ./.github/actions/docker-build
        with:
          tag: witnet/price-feeds-poller

  docker-run:
    name: Try some commands in Docker image
    runs-on: ubuntu-latest
    needs: ["docker-build"]
    steps:
      - name: Try to run main command
        run: docker run witnet/price-feeds-poller -h
      - name: Try to run witnet-toolkit
        run: docker run --entrypoint npx witnet/price-feeds-poller witnet-toolkit --version

